services:
  app:
    container_name: enovia
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
    ports:
      - "5001:5001"
    command: ["npm", "run", "start"]
    restart: always
